# Generated by Django 4.1.3 on 2022-11-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=110, unique=True)),
                ('content', models.TextField(max_length=800)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
